import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import './globals.css'
import { Toaster } from "@/components/ui/sonner";
import { cn } from '@/lib/utils'
import { SpeedInsights } from "@vercel/speed-insights/next"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({children}: {children: React.ReactNode}) {
  const session = await auth();

  return (
    <div>
      <SessionProvider session={session}>
      <html lang="fr">
        <body className={cn(inter.className, "bg-gray-100")}>
          <Toaster />
          {children}
        </body>
      </html>
    </SessionProvider>
    <SpeedInsights/>
    </div>
    
  )
}
